<?php

return [
    'PT Bank Rakyat Indonesia (Persero) Tbk',
    'PT Bank Mandiri (Persero) Tbk',
    'PT Bank Negara Indonesia (Persero) Tbk',
    'PT Bank Tabungan Negara (Persero) Tbk',
    'PT Bank Danamon Indonesia Tbk',
    'PT Bank Permata Tbk',
    'PT Bank Central Asia Tbk',
    'PT Bank Maybank Indonesia Tbk',
    'PT Bank Pan Indonesia Tbk',
    'PT Bank CIMB Niaga Tbk',
    'PT Bank UOB Indonesia',
    'PT Bank OCBC NISP Tbk',
    'PT Bank Artha Graha Internasional Tbk',
    'PT Bank Bumi Arta Tbk',
    'PT Bank HSBC Indonesia',
    'PT Bank JTrust Indonesia Tbk',
    'PT Bank Mayapada International Tbk',
    'PT Bank of India Indonesia Tbk',
    'PT Bank Muamalat Indonesia Tbk',
    'PT Bank Mestika Dharma Tbk',
    'PT Bank Shinhan Indonesia',
    'PT Bank Sinarmas Tbk',
    'PT Bank Maspion Indonesia Tbk',
    'PT Bank Ganesha Tbk',
    'PT Bank ICBC Indonesia',
    'PT Bank QNB Indonesia Tbk',
    'PT Bank Woori Saudara Indonesia 1906 Tbk',
    'PT Bank Mega Tbk',
    'PT Bank KB Bukopin Tbk',
    'PT Bank Syariah Indonesia Tbk',
    'PT Bank KEB Hana Indonesia',
    'PT Bank MNC Internasional Tbk',
    'PT Bank Raya Indonesia Tbk',
    'PT Bank SBI Indonesia',
    'PT Bank Mega Syariah',
    'PT Bank Index Selindo',
    'PT Bank Hibank Indonesia',
    'PT Bank China Construction Bank Indonesia Tbk',
    'PT Bank DBS Indonesia',
    'PT Bank Resona Perdania',
    'PT Bank Mizuho Indonesia',
    'PT Bank Capital Indonesia Tbk',
    'PT Bank BNP Paribas Indonesia',
    'PT Bank ANZ Indonesia',
    'PT Bank IBK Indonesia Tbk',
    'PT Bank Aladin Syariah Tbk',
    'PT Bank CTBC Indonesia',
    'PT Bank Commonwealth',
    'PT Bank Tabungan Pensiunan Nasional Tbk',
    'PT Bank Victoria Syariah',
    'PT Bank Jabar Banten Syariah',
    'PT Krom Bank Indonesia Tbk',
    'PT Bank Jasa Jakarta',
    'PT Bank Neo Commerce Tbk',
    'PT Bank Digital BCA',
    'PT Bank Nationalnobu Tbk',
    'PT Bank Ina Perdana Tbk',
    'PT Bank Panin Dubai Syariah Tbk',
    'PT Bank KB Bukopin Syariah',
    'PT Bank Sahabat Sampoerna',
    'PT Bank Oke Indonesia Tbk',
    'PT Bank Amar Indonesia',
    'PT Bank Seabank Indonesia',
    'PT Bank BCA Syariah',
    'PT Bank Jago Tbk',
    'PT Bank BTPN Syariah Tbk',
    'PT Bank Multiarta Sentosa Tbk',
    'PT Super Bank Indonesia',
    'PT Bank Mandiri Taspen',
    'PT Bank Victoria International Tbk',
    'PT Allo Bank Indonesia Tbk',
    'PT Bank Nano Syariah',

    'PT BPD Jawa Barat dan Banten Tbk',
    'PT BPD DKI',
    'PT BPD Daerah Istimewa Yogyakarta',
    'PT BPD Jawa Tengah',
    'PT BPD Jawa Timur Tbk',
    'PT BPD Jambi',
    'PT Bank Aceh Syariah',
    'PT BPD Sumatera Utara',
    'PT Bank Nagari',
    'PT BPD Riau Kepri Syariah',
    'PT BPD Sumatera Selatan dan Bangka Belitung',
    'PT BPD Lampung',
    'PT BPD Kalimantan Selatan',
    'PT BPD Kalimantan Barat',
    'PT BPD Kalimantan Timur dan Kalimantan Utara',
    'PT BPD Kalimantan Tengah',
    'PT BPD Sulawesi Selatan dan Sulawesi Barat',
    'PT BPD Sulawesi Utara dan Gorontalo',
    'PT Bank NTB Syariah',
    'PT BPD Bali',
    'PT BPD Nusa Tenggara Timur',
    'PT BPD Maluku dan Maluku Utara',
    'PT BPD Papua',
    'PT BPD Bengkulu',
    'PT BPD Sulawesi Tengah',
    'PT BPD Sulawesi Tenggara',
    'PT BPD Banten Tbk',
    'Citibank N.A.',
    'JP Morgan Chase Bank N.A.',
    'Bank of America N.A.',
    'MUFG Bank Ltd',
    'Standard Chartered Bank',
    'Deutsche Bank AG',
    'Bank of China (Hong Kong) Limited Cabang Jakarta',
];
