<?php

return [
    'PART & SERVICE',
    'SPARE PART',
    'FUEL',
    'LUBRICANT',
    'TIRE',
    'TOOLS',
    'SAFETY EQUIPMENT',
    'RENTAL EQUIPMENT',
    'TRANSPORT',
    'MOBILIZATION',
    'DEMOBILIZATION',
    'FABRICATION & WELDING',
    'REPAIR & MAINTENANCE',
    'OVERHAUL',
    'CIVIL WORK',
    'ROAD MAINTENANCE',
    'CAMP SUPPORT',
    'OFFICE SUPPORT',
    'GENERAL SUPPLIES',
    'SERVICE CONTRACTOR',
];
