<?php

return [
    'Pemeriksaan sebelum dijalankan' => [
        'Sticker commisioning',
        'Fatigue alarm',
        'High level alarm',
        'Dokumen kendaraan (STNK, Buku Kir)',
        'Kotak P3K',
        'Banyaknya air radiator (Engine radiator water level)',
        'Banyaknya oli mesin (Engine oil level)',
        'Banyaknya oli hydraulik (Hydraulic oil level)',
        'Banyaknya bahan bakar (Fuel level)',
        'Banyaknya air pencuci kaca (Windscreen washer water level)',
        'Periksa akan adanya kebocoran (Visual check for fuid leaks)',
        'Periksa botol pemadam / terisi penuh (Fire extinguisher / chane)',
        'Periksa kondisi seat belt / kerja baik (Seat belt condition working)',
        'Klakson (Horn)',
        'Penghapus kaca depan (wiper)',
        'Kaca spion (Mirrors)',
        'Buang endapan air dari tangki udara (Drain water air tank)',
        'Periksa keadaan ban 2 dan mur2nya (Visual check tire / wheel nuts)',
        'Lampu jauh dan dekat (Headlight high / low)',
        'Lampu parkir (Park lights)',
        'Lampu clearance / jarak (Clearance light)',
        'Lampu stop (Stop light)',
        'Lampu belakang (Tail light)',
        'Lampu mundur (Reverse light)',
        'Lampu kabin (Cabin lamp)',
        'Lampu kerja (Loading light)',
        'Lampu rotary (Rotary light)',
        'Lampu belok (Turn indicator)',
        'Lampu operasi (Operation light)',
        'Kondisi king pin : bengkok / aus / retak',
        'Kondisi turn table : Handle lock, safety latch',
        'Kondisi hose udara',
        'Kondisi hose hidrolik',
        'Kondisi fitting & coupling',
        'Kondisi brake chamber mover dan trailer',
        'Kondisi ganjal',
        'Box isolasi lengkap dengan penutup',
        'Kondisi jack & shoes'
    ],
    'Pemeriksaan bangian tanki' => [
        'Periksa adanya kebocoran tetesan atau rembesan pada dinding luar tanki',
        'Kondisi permukaan luar tanki',
        'Kondisi tutup kompartemen',
        'Kondisi hose-hose pengisian, nozzle',
        'Kondisi sambungan-sambungan pada hose dan tanker',
        'Jumlah perlengkapan pencegah tumpahan solar, absorbent pad atau boom pad',
        'Perlengkapan loading & unloading fuel tanker',
        'Tangga pagar, guard rail & pelindung rantai guard rail',
        'Ansorbant pad, kain lap (Majun)',
        'Kondisi ganjal (Wajib tersedia 2 buah & safety cone)',
        'Kondisi jack & shoes'
    ],
    'Pemeriksaan sesudah mesin hidup (check after starting) *JIKA RUSAK JANGAN DI OPERASIKAN' => [
        'Kemudi (Steering)',
        'Rem sevice (service brake)',
        'Trailer brake',
        'Pemeriksaan akhir shift (check and of shift)',
        'Kebersihan',
        'Kondisi kendaraan',
        'Kondisi dan perlengkapan peralatan didalam kendaraan'
    ]
];
